insert into public.software_catalog (
  name,
  category,
  target_roles,
  tags,
  description,
  pricing_model,
  website_url,
  key_features,
  pros_template,
  cons_template,
  is_active
)
values
  (
    'Notion',
    'Project Management',
    array['product manager', 'operations', 'founder'],
    array['knowledge-base', 'collaboration', 'docs'],
    '문서, 위키, 프로젝트 관리를 결합한 올인원 워크스페이스',
    'Free + Team',
    'https://www.notion.so',
    array['문서/위키', 'DB 기반 프로젝트 트래킹', '협업 코멘트', '템플릿'],
    array['빠른 도입', '유연한 커스터마이징', '협업 친화적'],
    array['복잡한 프로세스에는 설계 필요', '권한모델 세분화 한계'],
    true
  ),
  (
    'ClickUp',
    'Project Management',
    array['project manager', 'agency', 'operations'],
    array['tasks', 'collaboration', 'automation'],
    '태스크 중심의 팀 생산성 관리 플랫폼',
    'Free + Business',
    'https://clickup.com',
    array['태스크/스프린트', '자동화 룰', '대시보드', '문서 결합'],
    array['프로젝트 가시성 우수', '자동화 기본 제공'],
    array['초기 학습 곡선', '구성 복잡도'],
    true
  ),
  (
    'Asana',
    'Project Management',
    array['operations', 'marketing manager', 'pm'],
    array['workflows', 'task-management', 'collaboration'],
    '업무 흐름 시각화와 협업을 지원하는 프로젝트 툴',
    'Free + Premium',
    'https://asana.com',
    array['보드/타임라인', '목표 연계', '자동화', '리포팅'],
    array['직관적 UI', '팀 협업에 강함'],
    array['고급 기능은 유료', '복잡한 권한 모델은 제한'],
    true
  ),
  (
    'Jira',
    'Project Management',
    array['developer', 'engineering manager', 'scrum master'],
    array['agile', 'issue-tracking', 'sprints'],
    '애자일 개발팀을 위한 이슈 추적/스프린트 관리 도구',
    'Standard + Premium',
    'https://www.atlassian.com/software/jira',
    array['백로그/스프린트', '워크플로우 커스터마이징', '릴리즈 트래킹', '자동화'],
    array['개발팀 표준 도구', '확장성 높음'],
    array['비개발 직군 접근성 낮음', '운영 복잡도'],
    true
  ),
  (
    'Linear',
    'Project Management',
    array['developer', 'startup founder', 'product manager'],
    array['issue-tracking', 'fast-ui', 'engineering'],
    '빠른 속도와 단순한 UX의 개발 이슈 트래킹 도구',
    'Free + Team',
    'https://linear.app',
    array['이슈/로드맵', '사이클 관리', 'Git 연동'],
    array['속도와 사용성 우수', '개발 워크플로우 적합'],
    array['비개발 업무 범용성 제한'],
    true
  ),
  (
    'HubSpot CRM',
    'CRM',
    array['sales', 'marketing', 'customer success'],
    array['crm', 'pipeline', 'lead-management'],
    '리드 관리부터 세일즈 자동화까지 제공하는 CRM',
    'Free + Starter',
    'https://www.hubspot.com',
    array['연락처/딜 파이프라인', '이메일 추적', '리포트', '자동화'],
    array['초기 도입 용이', '마케팅 연계 강점'],
    array['고급 기능 비용 상승', '복잡한 커스텀은 제한'],
    true
  ),
  (
    'Salesforce',
    'CRM',
    array['enterprise sales', 'operations', 'admin'],
    array['crm', 'enterprise', 'automation'],
    '대규모 조직을 위한 엔터프라이즈 CRM 플랫폼',
    'Enterprise',
    'https://www.salesforce.com',
    array['고급 파이프라인', '권한/승인 플로우', 'AppExchange', '보고서'],
    array['확장성과 생태계 강력', '복잡한 프로세스 대응'],
    array['구축/운영 비용 높음', '전담 관리자 필요'],
    true
  ),
  (
    'Pipedrive',
    'CRM',
    array['smb sales', 'founder'],
    array['crm', 'pipeline', 'sales'],
    '중소팀을 위한 가벼운 세일즈 파이프라인 CRM',
    'Paid',
    'https://www.pipedrive.com',
    array['딜 파이프라인', '활동 관리', '자동 알림'],
    array['사용이 간단', '영업 집중 기능'],
    array['확장 기능 제한'],
    true
  ),
  (
    'Zoho CRM',
    'CRM',
    array['sales', 'operations'],
    array['crm', 'automation', 'analytics'],
    '비용 효율형 CRM + 업무 자동화 도구',
    'Freemium',
    'https://www.zoho.com/crm',
    array['리드/딜 관리', '워크플로우 자동화', '분석 대시보드'],
    array['가격 대비 기능 폭넓음'],
    array['UI 학습 필요'],
    true
  ),
  (
    'Mailchimp',
    'Marketing Automation',
    array['marketer', 'founder'],
    array['email-marketing', 'campaign', 'automation'],
    '이메일 캠페인 중심 마케팅 자동화 툴',
    'Freemium',
    'https://mailchimp.com',
    array['세그먼트', '자동 시나리오', 'A/B 테스트'],
    array['초기 마케팅 자동화 쉬움'],
    array['고급 시나리오는 제한'],
    true
  ),
  (
    'Klaviyo',
    'Marketing Automation',
    array['ecommerce marketer', 'crm manager'],
    array['retention', 'email', 'sms'],
    '이커머스 리텐션 중심 자동화 플랫폼',
    'Paid',
    'https://www.klaviyo.com',
    array['이벤트 기반 자동화', '고객 세분화', 'SMS/Email 통합'],
    array['리텐션 성과 개선에 강함'],
    array['초기 설정 난이도'],
    true
  ),
  (
    'Braze',
    'Marketing Automation',
    array['growth marketer', 'product marketer'],
    array['customer-engagement', 'automation', 'personalization'],
    '고급 고객 여정 오케스트레이션 도구',
    'Enterprise',
    'https://www.braze.com',
    array['멀티채널 오케스트레이션', '개인화', '실험'],
    array['고급 마케팅 운영 가능'],
    array['엔터프라이즈 비용'],
    true
  ),
  (
    'Intercom',
    'Customer Support',
    array['customer success', 'support'],
    array['support', 'live-chat', 'helpdesk'],
    '고객 메시징과 지원센터를 결합한 서비스 플랫폼',
    'Paid',
    'https://www.intercom.com',
    array['라이브챗', '헬프센터', '티켓팅', '봇'],
    array['고객 응대 품질 향상'],
    array['규모 확장 시 비용 증가'],
    true
  ),
  (
    'Zendesk',
    'Customer Support',
    array['support manager', 'operations'],
    array['ticketing', 'support', 'sla'],
    '티켓 기반 고객지원 운영 표준 툴',
    'Suite',
    'https://www.zendesk.com',
    array['티켓/SLA', '지식베이스', '옴니채널 지원'],
    array['운영 성숙도 향상', '기업 지원 기능 풍부'],
    array['설정 복잡도'],
    true
  ),
  (
    'Freshdesk',
    'Customer Support',
    array['support team', 'startup'],
    array['ticketing', 'automation', 'support'],
    '중소팀 친화형 고객지원 티켓 시스템',
    'Freemium',
    'https://www.freshworks.com/freshdesk',
    array['티켓 자동화', 'FAQ', 'SLA'],
    array['도입 난이도 낮음'],
    array['고급 맞춤 기능 제한'],
    true
  ),
  (
    'Airtable',
    'Internal Tooling',
    array['ops', 'pm', 'analyst'],
    array['database', 'no-code', 'workflow'],
    '스프레드시트 감성의 노코드 데이터베이스',
    'Freemium',
    'https://airtable.com',
    array['관계형 테이블', '자동화', '폼/뷰', '인터페이스'],
    array['내부 툴 MVP 구축 빠름'],
    array['복잡한 로직 확장 한계'],
    true
  ),
  (
    'Retool',
    'Internal Tooling',
    array['ops engineer', 'internal tools developer'],
    array['internal-tools', 'low-code', 'database'],
    '사내 운영 도구를 빠르게 만드는 로우코드 플랫폼',
    'Paid',
    'https://retool.com',
    array['DB/API 연결', '컴포넌트 빌더', '권한 관리'],
    array['개발 생산성 높음'],
    array['라이선스 비용', '벤더 종속성'],
    true
  ),
  (
    'Monday.com',
    'Project Management',
    array['operations', 'marketing', 'pm'],
    array['workflow', 'collaboration', 'automation'],
    '시각적 보드 기반 업무 운영 플랫폼',
    'Paid',
    'https://monday.com',
    array['보드/자동화', '대시보드', '템플릿'],
    array['비개발 직군 친화적'],
    array['세부 권한 설계 제약'],
    true
  ),
  (
    'Trello',
    'Project Management',
    array['small team', 'founder'],
    array['kanban', 'task-management', 'collaboration'],
    '가벼운 칸반 기반 태스크 관리 툴',
    'Freemium',
    'https://trello.com',
    array['칸반 보드', '카드 자동화', '간편 공유'],
    array['학습 부담 낮음'],
    array['복잡한 프로젝트에는 부족'],
    true
  ),
  (
    'Figma',
    'Design Collaboration',
    array['designer', 'product manager', 'developer'],
    array['design', 'collaboration', 'prototyping'],
    '디자인 협업 및 프로토타이핑 플랫폼',
    'Freemium',
    'https://www.figma.com',
    array['실시간 협업', '프로토타입', '디자인 시스템'],
    array['협업 속도 우수'],
    array['대규모 파일 성능 이슈 가능'],
    true
  ),
  (
    'Miro',
    'Collaboration',
    array['product manager', 'consultant', 'team lead'],
    array['whiteboard', 'ideation', 'workshop'],
    '온라인 화이트보드 협업 도구',
    'Freemium',
    'https://miro.com',
    array['브레인스토밍', '워크숍 보드', '템플릿'],
    array['원격 협업에 적합'],
    array['정형 데이터 관리에는 부적합'],
    true
  ),
  (
    'Google Analytics 4',
    'Data Analytics',
    array['marketer', 'analyst', 'founder'],
    array['analytics', 'web', 'events'],
    '웹/앱 이벤트 분석 도구',
    'Free',
    'https://analytics.google.com',
    array['이벤트 분석', '전환 추적', '세그먼트'],
    array['무료 기반 분석 가능'],
    array['학습 곡선 높음'],
    true
  ),
  (
    'Mixpanel',
    'Data Analytics',
    array['product analyst', 'growth'],
    array['product-analytics', 'funnel', 'retention'],
    '제품 지표 분석과 퍼널 최적화 플랫폼',
    'Freemium',
    'https://mixpanel.com',
    array['퍼널/리텐션', '코호트', '실험 분석'],
    array['제품 개선 인사이트 도출'],
    array['이벤트 설계 품질 의존'],
    true
  ),
  (
    'Amplitude',
    'Data Analytics',
    array['product manager', 'analyst'],
    array['product-analytics', 'behavior', 'insights'],
    '행동 데이터 기반 제품 분석 플랫폼',
    'Freemium',
    'https://amplitude.com',
    array['유저 행동 분석', '코호트', '여정 시각화'],
    array['제품 의사결정 강화'],
    array['초기 이벤트 모델링 필요'],
    true
  ),
  (
    'Tableau',
    'Data Analytics',
    array['data analyst', 'bi engineer'],
    array['dashboard', 'bi', 'visualization'],
    'BI 대시보드 시각화 솔루션',
    'Enterprise',
    'https://www.tableau.com',
    array['시각화 대시보드', '데이터 소스 연결', '권한 배포'],
    array['시각화 품질 높음'],
    array['라이선스 비용 높음'],
    true
  ),
  (
    'Power BI',
    'Data Analytics',
    array['analyst', 'operations'],
    array['dashboard', 'bi', 'microsoft'],
    '마이크로소프트 생태계 친화형 BI 도구',
    'Paid',
    'https://powerbi.microsoft.com',
    array['리포트/대시보드', '데이터 모델링', '팀 공유'],
    array['MS 제품군과 연동 우수'],
    array['복잡 모델링 학습 필요'],
    true
  ),
  (
    'QuickBooks',
    'Finance/Accounting',
    array['finance manager', 'startup founder'],
    array['accounting', 'finance', 'invoicing'],
    '중소기업 회계 및 청구 관리 도구',
    'Paid',
    'https://quickbooks.intuit.com',
    array['회계 장부', '청구서', '지출 추적'],
    array['회계 자동화 기본 제공'],
    array['지역별 세무 요구는 별도 검토 필요'],
    true
  ),
  (
    'Xero',
    'Finance/Accounting',
    array['finance', 'operations'],
    array['accounting', 'bookkeeping', 'invoicing'],
    '클라우드 기반 중소기업 회계 플랫폼',
    'Paid',
    'https://www.xero.com',
    array['은행 연동', '장부 자동화', '청구 관리'],
    array['UI 사용성 우수'],
    array['특수 회계 처리 한계'],
    true
  ),
  (
    'Workable',
    'HR/Recruiting',
    array['hr manager', 'recruiter'],
    array['ats', 'hiring', 'recruiting'],
    '채용 파이프라인 운영용 ATS 솔루션',
    'Paid',
    'https://www.workable.com',
    array['채용 파이프라인', '면접 스케줄링', '후보자 DB'],
    array['채용 운영 표준화'],
    array['고급 브랜딩 커스텀 제한'],
    true
  ),
  (
    'Greenhouse',
    'HR/Recruiting',
    array['hr', 'talent acquisition'],
    array['ats', 'hiring', 'enterprise'],
    '대규모 채용 프로세스에 강한 ATS',
    'Enterprise',
    'https://www.greenhouse.com',
    array['채용 단계 설계', '면접 평가', '리포트'],
    array['채용 품질 관리 강화'],
    array['초기 셋업 비용'],
    true
  ),
  (
    'Calendly',
    'Productivity',
    array['sales', 'customer success', 'recruiter'],
    array['scheduling', 'calendar', 'automation'],
    '미팅 일정 조율 자동화 도구',
    'Freemium',
    'https://calendly.com',
    array['일정 슬롯 공유', '캘린더 연동', '리마인더 자동화'],
    array['커뮤니케이션 비용 절감'],
    array['복합 워크플로우에는 한계'],
    true
  );
